import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#050b14" },
  app: { flex: 1, backgroundColor: "#050b14" },
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 14 },
  logo: { color: "#f8fafc", fontSize: 30, fontWeight: "900" },
  sub: { color: "#94a3b8", marginTop: 4, fontSize: 14 },
  content: { flex: 1, paddingHorizontal: 16 },
  card: { backgroundColor: "#0f172a", borderRadius: 22, padding: 18, marginBottom: 14, borderWidth: 1, borderColor: "#1e293b" },
  cardTitle: { color: "#38bdf8", fontWeight: "800", fontSize: 16, marginBottom: 10 },
  bigText: { color: "#f8fafc", fontSize: 24, fontWeight: "900", marginBottom: 8 },
  bigTextSmall: { color: "#f8fafc", fontSize: 22, fontWeight: "900", marginBottom: 2 },
  text: { color: "#e2e8f0", fontSize: 15, lineHeight: 22 },
  muted: { color: "#94a3b8", fontSize: 14, lineHeight: 21 },
  tabs: { flexDirection: "row", paddingHorizontal: 10, paddingTop: 8, paddingBottom: 12, borderTopWidth: 1, borderTopColor: "#1e293b", backgroundColor: "#07111f" },
  tabButton: { flex: 1, alignItems: "center", paddingVertical: 8, borderRadius: 16 },
  tabActive: { backgroundColor: "#102033" },
  tabLabel: { color: "#64748b", fontSize: 11, marginTop: 3 },
  tabLabelActive: { color: "#38bdf8", fontWeight: "800" },
  monthHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 14 },
  monthTitle: { color: "#f8fafc", fontSize: 22, fontWeight: "900" },
  smallButton: { backgroundColor: "#0f172a", borderRadius: 14, paddingHorizontal: 16, paddingVertical: 8, borderWidth: 1, borderColor: "#1e293b" },
  buttonText: { color: "#f8fafc", fontSize: 20, fontWeight: "900" },
  actionRow: { flexDirection: "row", gap: 10, marginBottom: 10 },
  actionButton: { flex: 1, backgroundColor: "#0f172a", padding: 12, borderRadius: 16, borderWidth: 1, borderColor: "#1e293b" },
  wideButton: { backgroundColor: "#0f172a", padding: 12, borderRadius: 16, borderWidth: 1, borderColor: "#1e293b", marginBottom: 14 },
  actionText: { color: "#e2e8f0", fontSize: 13, fontWeight: "700", textAlign: "center" },
  calendar: { flexDirection: "row", flexWrap: "wrap", backgroundColor: "#0f172a", borderRadius: 22, padding: 8, marginBottom: 14, borderWidth: 1, borderColor: "#1e293b" },
  weekday: { width: "14.285%", textAlign: "center", color: "#64748b", fontSize: 12, fontWeight: "800", paddingVertical: 8 },
  day: { width: "14.285%", minHeight: 82, padding: 4, borderRadius: 14, alignItems: "center" },
  dayNumber: { color: "#f8fafc", fontSize: 13, fontWeight: "800", marginBottom: 4 },
  shiftBadge: { minWidth: 36, paddingVertical: 3, paddingHorizontal: 4, borderRadius: 9, alignItems: "center", marginBottom: 3 },
  shiftText: { color: "#020617", fontSize: 10, fontWeight: "900" },
  wasteRow: { flexDirection: "row", flexWrap: "wrap", justifyContent: "center", minHeight: 17 },
  wasteIcon: { marginHorizontal: 1 },
  unknownMini: { color: "#fca5a5", fontSize: 11, fontWeight: "900" },
  taskCountBadge: { marginTop: 2, backgroundColor: "#1e293b", minWidth: 18, height: 18, borderRadius: 9, alignItems: "center", justifyContent: "center" },
  taskCountText: { color: "#e2e8f0", fontSize: 10, fontWeight: "800" },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.72)", justifyContent: "flex-end" },
  modal: { backgroundColor: "#0f172a", borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 20, maxHeight: "90%", borderWidth: 1, borderColor: "#1e293b" },
  modalTitle: { color: "#f8fafc", fontSize: 22, fontWeight: "900", marginBottom: 14 },
  detailBlock: { backgroundColor: "#020617", borderRadius: 18, padding: 14, marginBottom: 12, borderWidth: 1, borderColor: "#1e293b" },
  detailShiftRow: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
  detailWasteRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  input: { backgroundColor: "#020617", color: "#f8fafc", borderWidth: 1, borderColor: "#1e293b", borderRadius: 16, padding: 14, marginBottom: 10, fontSize: 15 },
  importBox: { minHeight: 130, textAlignVertical: "top", marginTop: 12 },
  primaryButton: { backgroundColor: "#38bdf8", padding: 15, borderRadius: 18, alignItems: "center", marginTop: 8 },
  primaryButtonText: { color: "#020617", fontWeight: "900", fontSize: 15 },
  secondaryButton: { backgroundColor: "#172554", padding: 14, borderRadius: 18, alignItems: "center", marginTop: 10 },
  secondaryButtonText: { color: "#bfdbfe", fontWeight: "800" },
  warningButton: { backgroundColor: "#450a0a", padding: 12, borderRadius: 16, alignItems: "center", marginTop: 8 },
  warningButtonText: { color: "#fecaca", fontWeight: "900" },
  closeButton: { padding: 15, borderRadius: 18, alignItems: "center", marginTop: 8 },
  closeButtonText: { color: "#94a3b8", fontWeight: "800" },
  shiftOption: { flexDirection: "row", alignItems: "center", backgroundColor: "#020617", padding: 12, borderRadius: 16, marginBottom: 8, borderWidth: 1, borderColor: "#1e293b" },
  colorDot: { width: 14, height: 14, borderRadius: 7, marginRight: 10 },
  shiftOptionCode: { color: "#f8fafc", fontWeight: "800", fontSize: 15 },
  shiftOptionTime: { color: "#94a3b8", fontSize: 13, marginTop: 2 },
  deleteOption: { padding: 14, alignItems: "center" },
  deleteText: { color: "#f87171", fontWeight: "800" },
  unknownBox: { marginTop: 14, backgroundColor: "#020617", borderRadius: 18, padding: 12, borderWidth: 1, borderColor: "#7f1d1d" },
  unknownItem: { backgroundColor: "#450a0a", borderRadius: 14, padding: 12, marginTop: 8 },
  unknownText: { color: "#fecaca", fontWeight: "800" },
  task: { flexDirection: "row", alignItems: "center", paddingVertical: 8 },
  taskCheck: { color: "#38bdf8", fontSize: 20, marginRight: 10 },
  taskText: { color: "#e2e8f0", fontSize: 15 },
  dayTaskRow: { flexDirection: "row", alignItems: "center", backgroundColor: "#020617", borderRadius: 14, padding: 10, marginBottom: 8, gap: 8 },
  dayTaskText: { color: "#e2e8f0", fontSize: 14, flex: 1 },
  dayTaskTextDone: { color: "#64748b", textDecorationLine: "line-through" },
  templateRow: { flexDirection: "row", alignItems: "center", paddingVertical: 8 },
  dangerButton: { backgroundColor: "#450a0a", padding: 15, borderRadius: 18, alignItems: "center", marginTop: 12, marginBottom: 20 },
  dangerButtonText: { color: "#fecaca", fontWeight: "900", fontSize: 15 },
});
